language: java

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# Java 10 "Oracle JDK" (not yet provided by Travis CI)
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
# Java 10 "OpenJDK"
    - env: JDK='OpenJDK 10' JACOCO='-PenableJaCoCo'
      install: . ./install-jdk.sh -F 10 -L GPL
# Java 11 "Oracle JDK"
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL

install:
  - echo "Downloading Maven 3.0";
  - wget https://archive.apache.org/dist/maven/binaries/apache-maven-3.0-bin.zip || travis_terminate 1
  - unzip -qq apache-maven-3.0-bin.zip || travis_terminate 1
  - export M2_HOME=$PWD/apache-maven-3.0
  - export PATH=$M2_HOME/bin:$PATH

script:
  - mvn -version
  - cd asta4d-core
  - mvn test
  - cd ../asta4d-web
  - mvn test
